name: Run tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        sudo apt-get install python3-apt software-properties-common
        sudo ln -s /usr/lib/python3/dist-packages/apt_pkg.cpython-36m-x86_64-linux-gnu.so \
          /usr/lib/python3/dist-packages/apt_pkg.so
          
        ls /usr/lib/python3/dist-packages/apt*
        
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements.dev.txt
    - name: Run tests
      run: python3 -m pytest
      env:
        NGROK_TOKEN: ${{secrets.NGROK_TOKEN}} 
