name: Run tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        sudo python3 -m pip install --upgrade pip
        sudo pip3 install -r requirements.txt -r requirements.dev.txt
        
        sudo apt-get update && sudo apt-get install -y python-apt
    - name: Run tests
      run: sudo python3 -m pytest
      env:
        NGROK_TOKEN: ${{secrets.NGROK_TOKEN}} 
